export default {
  GILROY: {
    ThinItalic: 'Gilroy-ThinItalic',
    Light: 'Gilroy-Light',
    Bold: 'Gilroy-Bold',
    Heavy: 'Gilroy-Heavy',
    BoldItalic: 'Gilroy-BoldItalic',
    SemiBold: 'Gilroy-SemiBold',
    ExtraBold: 'Gilroy-ExtraBold',
    MediumItalic: 'Gilroy-MediumItalic',
    Black: 'Gilroy-Black',
    ExtraBoldItalic: 'Gilroy-ExtraBoldItalic',
    RegularItalic: 'Gilroy-RegularItalic',
    UltraLight: 'Gilroy-UltraLight',
    Medium: 'Gilroy-Medium',
    HeavyItalic: 'Gilroy-HeavyItalic',
    SemiBoldItalic: 'Gilroy-SemiBoldItalic',
    UltraLightItalic: 'Gilroy-UltraLightItalic',
    BlackItalic: 'Gilroy-BlackItalic',
    Regular: 'Gilroy-Regular',
    Thin: 'Gilroy-Thin',
    LightItalic: 'Gilroy-LightItalic',
  },
};
