import React from 'react';
import {Text} from 'react-native';

export const strings = {
  appName: 'SavozApp',
  emailRequired: 'Email is required.\nPlease enter email address',
  enterValidEmail: 'Please enter a valid email',
  emailAddress: 'Email address',
  sendLink: 'Send link',
  landingText: 'Quick grocery delivery at your doorstep',
  enterNewPassword:
    'Enter new password & it must be different from previous passwords',
  continueAsGuest: 'Continue as guest',
  pleaseEnterPassword: 'Please enter password',
  enterConfirmPassword: 'Please enter confirm password',
  passwordMinLength: 'Password must be at-least 8 char long',
  confirmPassNotMatch: 'Confirm Password not matched with the Password',
  passwordUpdated: 'Password Updated Successfully',
  ok: 'OK',
  password: 'Password',
  confirmPassword: 'Confirm password',
  resetPassword: 'Reset password',
  signIn: 'Sign in',
  emailPlaceHolder: 'Username / Email address',
  forgotPass: 'Forgot Password?',
  login: 'Log in',
  signUp: 'Sign Up',
  dontHaveAnAccount: 'Don’t have an account?',
  titleRequired: 'Title required, please select one',
  firstNameRequired: 'First Name required (minimum 3 char)',
  lastNameRequired: 'Last Name required (minimum 3 char)',
  phoneRequired: 'Phone number is required, please enter a valid number',
  firstName: 'First name',
  lastName: 'Last name',
  phoneNumber: 'Phone number',
  haveAnAccount: 'Have an account?',
  removeItem: 'Remove Item',
  areYouSureYouWantToRemove:
    'Are you sure you want to remove this item from cart?',
  yes: 'Yes',
  no: 'No',
  updateCart: 'Update Cart',
  noProductInCart: 'No product in cart',
  myCart: 'My Cart',
  checkout: 'Checkout',
  pleaseEnterCardDetails: 'Please enter card details',
  cardPlaceHolder: '4242 4242 4242 4242',
  done: 'Done',
  pleaseProvideValidAddressToContinue:
    'Please provide a valid address to continue',
  pleaseAddCardForPayment: 'Please add card for payment',
  youWillGetCashBack: 'You will get 5$ cash back if you pickup from the store',
  deliveryAddress: 'Delivery Address',
  enterAddressHere: 'Enter Address here',
  enterPromoCodeHere: 'Enter promo code here',
  apply: 'Apply',
  orderSummary: 'Order Summary',
  subTotal: 'Sub Total',
  taxes: 'Taxes',
  discounts: 'Discounts',
  total: 'Total',
  pickup: 'Pickup',
  cashBack: '5$ cash back',
  doorSteps: 'Door Step',
  paymentMethod: 'Payment Method',
  addCardForPayment: 'Add Card for payment',
  minimumOrderStart: 'Minimum order amount require is ',
  minimumOrderEnd: '$ to proceed with the cart.',
  checkOut: 'Check Out',
  placeOrder: 'Place Order',
  favourites: 'Favourites',
  searchHere: 'Search here',
  yourOrderHasBeenAccepted: 'Your order has been accepted',
  yourItemsHasBeenPlaced:
    'Your items has been placed and is on it’s way to being processed',
  trackYourOrder: 'Track your order',
  backToHome: 'Back to home',
  orderID: 'Order id # :',
  date: 'Date :',
  totalPrice: 'Total Price :',
  orderStatus: 'Order status :',
  yourRated: 'Your rated :',
  ratings: '4.9',
  myOrders: 'My Orders',
  addToCart: 'Add to cart',
  rateExperience: 'Rate your experience',
  itemAddedSuccessfully: 'Item added to cart successfully',
  profileUpdatedSuccessfully: 'Profile updated successfully',
  cancel: 'Cancel',
  delete: 'Delete',
  profileDeleteConfirmation:
    'Are you really want to delete your profile? It will delete your acoount and other information permanently',
  profile: 'Profile',
  dob: 'Date of birth',
  deleteYourProfile: 'Delete your profile',
  save: 'Save',
  editProfile: 'Edit Profile',
  logout: 'LOGOUT',
  areYouSureLogout: 'Are you sure you want to Logout?',
  guestAccountMessage:
    'This is a Guest account.\nPlease logout from here and Login with your account.',
  notifications: 'Notifications',
  log_in: 'Login',
  log_out: 'Logout',
  quantityUpdated: 'Quantity updated in cart for this product',
  // contactBody: 'Contact/Support details\n1 (416) 739 9719\n\n',
  contactBody: '',
  contactSubject: 'Support Help',
  areYouNew: 'Are you new? Sign Up',
  free: 'free',
  noItemInFavourite: 'There is no favourite item to show',
  noOrderToDisplay: "There's no order to display here",
  noProductAvailable: 'No Product available currently for this category',
  addProductsToCart: 'Your cart is empty.\nPlease add products.',
  grocerryDelivered: 'Your Grocerry delivered',
  cancelOrder: 'Cancel Order',
  deliveryTime: 'Delivery Time',
  mints15: '15 minutes',
  yourAddress: 'Your Address',
  fakeadress: 'Lahore, Pakistan',
};

export default strings;
