import {StyleSheet} from 'react-native';
import {Colors, height, IS_IPHONE_X} from '../../../constants';
import Fonts from '../../../constants/Fonts';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.WHITE.default,
  },
  profilePicContainer: {
    marginTop: 24,
    alignSelf: 'center',
    borderRadius: 100,
    // elevation: 7,
    borderWidth: 0.3,
    borderColor: Colors.BORDER.default,
  },
  profilePic: {
    width: 112,
    height: 112,
    resizeMode: 'cover',
    borderRadius: 100,
    // elevation: 7,
    // borderWidth: 1,
  },
  cameraIconContainer: {
    right: 0,
    bottom: 0,
    position: 'absolute',
  },
  cameraIcon: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  inputField: {
    alignSelf: 'center',
    marginTop: '5%',
  },
  rowContainer: {
    flexDirection: 'row',
    paddingHorizontal: '5%',
    justifyContent: 'space-between',
  },
  buttonStyle: {
    alignSelf: 'center',
    marginBottom: '8%',
  },
  deleteIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  deleteContainer: {
    marginTop: 20,
    marginLeft: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  delete: {
    marginLeft: 8,
    fontSize: 14,
    fontFamily: Fonts.GILROY.Medium,
    color: Colors.RED.default,
  },
  phoneInputContainer: {
    paddingLeft: 20,
    backgroundColor: Colors.WHITE.default,
    width: '90%',
    height: IS_IPHONE_X ? height * 0.06 : height * 0.07,
    borderWidth: 1,
    borderColor: Colors.BORDER.default,
    borderRadius: 8,
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 20,
    overflow: 'hidden',
  },
  inputStyle: {
    alignSelf: 'flex-start',
    width: '98%',
    backgroundColor: Colors.WHITE.default,
    fontSize: 14,
    flex: 1,
  },
  absoluteScreen: {
    position: 'absolute',
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  alertBody: {
    backgroundColor: Colors.WHITE.default,
    width: '90%',
    // height: 100,
    padding: 20,
    // borderWidth: 1,
    borderRadius: 20,
    shadowColor: Colors.BLACK.default,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  textBold: {
    textAlign: 'center',
    fontFamily: Fonts.GILROY.SemiBold,
    fontSize: 24,
    marginVertical: 20,
  },
  textDescription: {
    textAlign: 'center',
    fontFamily: Fonts.GILROY.Medium,
    fontSize: 14,
    width: '95%',
    alignSelf: 'center',
    lineHeight: 20,
    color: Colors.GRAY.light_2,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 30,
    marginBottom: 15,
  },
  datePickerBox: {
    width: '90%',
    height: IS_IPHONE_X ? height * 0.06 : height * 0.07,
    borderWidth: 1,
    borderColor: Colors.BORDER.default,
    borderRadius: 8,
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 20,
    // overflow: 'hidden',
    // alignItems: 'center'
  },
  addressBox: {
    width: '90%',
    minHeight: IS_IPHONE_X ? height * 0.06 : height * 0.07,
    borderWidth: 1,
    borderColor: Colors.BORDER.default,
    borderRadius: 8,
    // justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 20,
    overflow: 'hidden',
  },
  dobText: {
    fontSize: 14,
    fontFamily: Fonts.GILROY.Medium,
    padding: 0,
    paddingHorizontal: 15,
    color: 'rgba(0, 0, 0, 0.6)',
  },
});
