import {StyleSheet, Platform} from 'react-native';
import {Colors, height, width} from '../../constants';
import Fonts from '../../constants/Fonts';

export default StyleSheet.create({
  favIconCon: {
    alignSelf: 'flex-end',
    position: 'absolute',
    // backgroundColor: 'blue',
    paddingLeft: 10,
  },
  favIcon: {
    width: 16.2,
    height: 14.3,
    resizeMode: 'contain',
  },
  modalCon: {
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
    backgroundColor: Colors.WHITE.default,
    width: '100%',
    paddingBottom: Platform.OS === 'ios' ? '7%' : 0,
    maxHeight: height * 0.9,
  },
  transparentView: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    left: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  barCon: {
    padding: '4%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bar: {
    width: '18%',
    height: 4,
    borderRadius: 3,
    backgroundColor: Colors.BACKGROUND.gray,
  },
  productNameModal: {
    color: Colors.BLACK.default,
    fontFamily: Fonts.GILROY.Bold,
    fontSize: 24,
  },
  productQuantityModal: {
    marginTop: '2%',
    color: Colors.GRAY.default,
    fontFamily: Fonts.GILROY.Medium,
    fontSize: 16,
  },
  productDetailsModal: {
    marginTop: '5%',
    color: Colors.GRAY.default,
    fontFamily: Fonts.GILROY.Medium,
    fontSize: 14,
    lineHeight: 16,
  },
  priceContainer: {
    alignItems: 'center',
    marginTop: '7%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  productPriceModal: {
    color: Colors.BLACK.default,
    fontFamily: Fonts.GILROY.Medium,
    fontSize: 24,
  },
  countText: {
    paddingHorizontal: '4.5%',
    color: Colors.BLACK.default,
    fontFamily: Fonts.GILROY.SemiBold,
    fontSize: 18,
  },
  icCount: {
    width: 20,
    height: 20,
    tintColor: Colors.WHITE.default,
    resizeMode: 'contain',
  },
  modalCounterContainer: {
    marginTop: '11%',
    marginBottom: '5%',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: 50,
    backgroundColor: Colors.ORANGE.default,
    borderRadius: 35,
    flexDirection: 'row',
    // paddingHorizontal: '7%',
  },
  buttonText: {
    color: Colors.WHITE.default,
    // fontFamily: Fonts.GILROY.Medium,
    fontFamily: Fonts.GILROY.Bold,
    fontSize: 16,
  },
  imgProduct: {
    // marginBottom: '10%',
    resizeMode: 'contain',
    width: '100%',
    // aspectRatio: 2,
    // width: 375,
    // height: 217,
    alignSelf: 'center',
    // borderWidth: 1,
  },
  // =====================================
  activeDott: {
    marginHorizontal: 2,
    width: 20,
    height: 5,
    borderRadius: 5,
    backgroundColor: 'orange',
  },
  dash: {
    width: 20,
    height: 6,
    borderRadius: 3,
    marginHorizontal: 3,
    backgroundColor: Colors.ORANGE.default,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 13,
    marginHorizontal: 3,
    backgroundColor: Colors.ORANGE.default,
    opacity: 0.4,
  },
  closeIconBtn: {
    // position: 'absolute',
    paddingBottom: 10,
    paddingRight: 10,
    alignSelf: 'flex-start',
    // borderWidth: 1,
  },
  closeIcon: {
    width: 15,
    height: 15,
    resizeMode: 'contain',
    tintColor: Colors.BLACK.default,
  },
  dotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginTop: 10,
    alignSelf: 'center',
    marginBottom: 20,
  },
  counterBtn: {
    // borderWidth: 1,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: '7%',
  },
  addIcon: {
    height: 30,
    width: 30,
    resizeMode: 'contain',
  },
  addBtn: {
    alignSelf: 'flex-end',
    // marginTop: '11%',
    // borderWidth: 1,
    paddingTop: '10%',
    paddingHorizontal: '5%',
    marginBottom: '5%',
  },
});
