import {StyleSheet, Platform} from 'react-native';
import {Colors, width} from '../../../../constants';
import Fonts from '../../../../constants/Fonts';

export default StyleSheet.create({
  addressBarContainer: {
    height: 40,
    width: '100%',
    alignSelf: 'center',
    borderRadius: 8,
    backgroundColor: Colors.GRAY.light,
    marginVertical: 10,
    alignItems: 'center',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  iconSmall: {
    height: 20,
    width: 20,
    resizeMode: 'contain',
  },
  addBarOrangeBox: {
    backgroundColor: Colors.ORANGE.default,
    flexDirection: 'row',
    height: 40,
    alignItems: 'center',
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  timeText: {
    fontFamily: Fonts.GILROY.Bold,
    // fontFamily: Fonts.GILROY.Medium,
    fontSize: 12,
    marginStart: 10,
    width: 35,
    color: Colors.WHITE.default,
    lineHeight: 14,
  },
  searchContainer: {
    paddingHorizontal: '5%',
  },
  searchInput: {
    fontSize: 14,
    fontFamily: Fonts.GILROY.Regular,
    flex: 1,
    padding: 0,
  },
  placeHolderText: {
    fontFamily: Fonts.GILROY.Regular,
  },
  listItemContainer: {
    backgroundColor: '#D1FAE5',
    borderRadius: 10,
    marginTop: 20,
  },
  listItemText: {
    marginTop: Platform.OS === 'ios' ? '9%' : '7%',
    margin: '6%',
    fontSize: Platform.OS === 'ios' ? 18 : 16,
    color: Colors.BLACK.default,
    fontFamily: Fonts.GILROY.Medium,
  },
  bannerCon: {
    backgroundColor: Colors.BACKGROUND.orange,
    width: '100%',
    height: 147,
    borderRadius: 8,
    marginTop: 10,
  },
  bannerMargin: {
    margin: '6%',
  },
  bannerTextBold: {
    color: Colors.BLACK.default,
    fontFamily: Fonts.GILROY.Bold,
    fontSize: 18,
  },
  bannerTextLight: {
    marginTop: 7,
    color: Colors.BLACK.default,
    fontFamily: Fonts.GILROY.Medium,
    fontSize: 12,
  },
  bannerTextOffer: {
    fontFamily: Fonts.GILROY.Bold,
    color: Colors.ORANGE.default,
    fontSize: 18,
    lineHeight: 24,
    marginTop: 10,
  },
  bannerBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    backgroundColor: Colors.ORANGE.default,
    borderRadius: 8,
    width: '30%',
    height: 26,
  },
  bannerBtnText: {
    fontFamily: Fonts.GILROY.SemiBold,
    textAlign: 'center',
    alignSelf: 'center',
    fontSize: 12,
    color: Colors.WHITE.default,
  },
  addressText: {
    fontFamily: Fonts.GILROY.Bold,
    // fontFamily: Fonts.GILROY.Medium,
    fontSize: 14,
    color: Colors.BLACK.slateBlack,
    width: '65%',
  },
  modalCon: {
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
    backgroundColor: Colors.WHITE.default,
    width: '100%',
    paddingBottom: '10%',
  },
  transparentView: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    left: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  barCon: {
    padding: '4%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bar: {
    width: '18%',
    height: 4,
    borderRadius: 3,
    backgroundColor: Colors.BACKGROUND.gray,
  },
  buttonsCon: {
    flex: 1,
    marginTop: '4%',
    marginHorizontal: '5%',
  },
  modalBtn: {
    alignItems: 'center',
    width: '100%',
    height: 50,
    borderColor: Colors.ORANGE.default,
    borderRadius: 8,
    flexDirection: 'row',
    borderWidth: 1,
  },
  buttonText: {
    marginStart: '4%',
    fontFamily: Fonts.GILROY.Medium,
    fontSize: 16,
  },
  addImgContainer: {
    position: 'absolute',
    right: 0,
  },
  addImageStyle: {
    height: 147,
    width: 147,
    resizeMode: 'contain',
  },
});
